[package]
name = "metronome"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
crossterm = { version = "0.28.1", features = ["event-stream"] }
ratatui = "0.26.0"
rodio = "0.19.0"
tokio = { version = "1.0", features = ["full"] }
