[package]
name = "metronome"
version = "0.2.0"
edition = "2024"

[profile.release]
lto = true
strip = true

[dependencies]
clap = "4.5"
crossterm = { version = "0.29", features = ["event-stream"] }
ratatui = "0.29"
rodio = "0.20"
tokio = { version = "1", features = ["full"] }
